In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [7]:
a= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
print(a.ndim)

2


In [9]:
a.shape

(3, 3)

In [12]:
a.size

9

In [13]:
a.itemsize

4

In [15]:
a[:,2]

array([3, 6, 9])

In [22]:
b=np.zeros([3,3],dtype="int")
b

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [23]:
c=np.ones([3,3],dtype="int")
c

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [27]:
d=np.copyto(b,c)
print(b)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [28]:
np.full([3,3],100)

array([[100, 100, 100],
       [100, 100, 100],
       [100, 100, 100]])

In [31]:
np.random.rand(4,4)

array([[0.79342582, 0.09070803, 0.64184625, 0.72665697],
       [0.86493283, 0.41622388, 0.8838214 , 0.37774834],
       [0.68147359, 0.86138888, 0.9801054 , 0.78463354],
       [0.29361831, 0.39052434, 0.38499745, 0.13804963]])

In [32]:
np.random.randint(5,10,size=(3,3))

array([[6, 8, 7],
       [5, 6, 9],
       [7, 9, 5]])

In [33]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
np.sin(a)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

In [37]:
np.reshape(a,9)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [44]:
m=np.arange(8)
print(m)

[0 1 2 3 4 5 6 7]


In [45]:
np.split(m,4)

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7])]

In [46]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
np.delete(a,[1,2,3])

array([1, 5, 6, 7, 8, 9])

In [49]:
np.rot90(a,1,(1,0))

array([[7, 4, 1],
       [8, 5, 2],
       [9, 6, 3]])